### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by vicentefederico** [tcarlsen/lovelace-screensaver#6]
It doesn't work for me.
 
I didn't have the ui-lovelace.yml file. create it and paste the code. 

the screensaver is activated for a while but does not download any photos. the screen goes blank

![image](https://user-images.githubusercontent.com/42210430/102612612-ce83ef80-410f-11eb-9e90-27960af3cd36.png)
the requests to the api do not fill either

**Comment by tcarlsen** [comment]
seems like something in your setup is blocking the api from unsplash. try open the dev tools in chrome while havin gthe screensaver running and check the console and network tab

**Comment by fgvicente** [comment]
apparently does not authenticate (401)
GET https://api.unsplash.com/search/photos?query=nature&per_page=21&orientation=landscape&page=1 401
I don't understand what could be happening
